### ISSUE TITLE
break main file into modules

### ISSUE THREAD

**Issue by v0idpwn** [v0idpwn/2dqg#8]

**Comment by venugopaldeekonda1** [comment]
Can this be elaborated? main file to modules???

**Comment by v0idpwn** [comment]
I'm sorry if I wasnt clear. 

Currently, I have only one python file, where all functions are. I want to separate it into modules based in the functions nature. For instance, one module for database functions.

**Comment by Shaphil** [comment]
@v0idpwn I have broken your application into smaller pieces. will send you a PR in a while.
